// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pustypifhfedqjiuxgmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1c3R5cGlmaGZlZHFqaXV4Z21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDE0MDAsImV4cCI6MjA1OTcxNzQwMH0.18E8kjM-JpZfp7xYXNP8ilHDtaN0W_4Y-4n0fEHB4jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);